name: uber_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_locales:


  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  firebase_database: ^9.0.13
  rxdart: ^0.27.3
  google_maps_flutter: ^2.1.4
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  google_maps_webservice: ^0.0.19
  location: ^4.3.0
  uuid: ^3.0.6
  lottie: ^1.3.0
  geoflutterfire: ^3.0.3
  http: ^0.13.4
  fluttertoast: ^8.0.9
  timer_builder: ^2.0.0
  url_launcher: ^6.1.3
  map_picker: ^0.0.3
  place_picker: ^0.9.20-nullsafety
  firebase_core: ^1.17.1
  provider: ^6.0.3
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^10.1.0
  animated_text_kit: ^4.2.1
  flutter_geofire: ^2.0.1
  assets_audio_player: ^3.0.4+3
  smooth_star_rating_nsafe: ^1.0.0+1
  firebase_messaging: ^11.4.2
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/locales/
    - music/music_notification.mp3

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
